### ISSUE TITLE
Maximum call stack issue after upgrading angular 2.0.0.rc.4, tns-core 2.2.1

### ISSUE THREAD

**Issue by raosrinivas1983** [ntrp/nativescript-ng2-drawer-seed#2]
Here is the full stack trace,

`S: Unhandled Promise rejection: Maximum call stack size exceeded ; Zone: <root> ; Task: Promise.then ; Value: RangeError: Maximum call stack size exceeded Rang
aximum call stack size exceeded                                                                                                                                 
JS:     at new ZoneAwarePromise (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js:470:17)                  
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js
:16                                                                                                                                                             
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js
:16                                                                                                                                                             
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js
:16                                                                                                                                                             
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js
0:1                                                                                                                                                             
JS:     at ZoneAwarePromise.NativePromiseProtototype.then (/data/data/org.nativescript.nativescriptng2drawerseed/files/app/tns_modules/zone.js/dist/zone-node.js`

**Comment by ntrp** [comment]
Updated libraries and code to work with current drawer and tns tooling.
